version: "{build}"
clone_folder: c:\go\src\github.com\Azure\draft
environment:
  GOPATH: c:\go
  PATH: c:\ProgramData\bin;$(PATH)
install:
  - ps: iex ((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/fishworks/gofish/master/scripts/install.ps1'))
  - gofish init
  - gofish install dep
  - dep ensure
build: "off"
deploy: "off"
test_script:
  - go build ./...
  - go test ./...
